### ISSUE TITLE
Categorical should take a sequence *or* a map

### ISSUE THREAD

**Issue by Schaechtle** [probcomp/Gen.clj#57]
### We want categoricals to take maps from key to probability as input

Currently, the following is works fine:
```clojure
(dist/categorical [0.1 0.9])
    1
```
But this throws an error:
```clojure
(dist/categorical {:foo 0.1 :bar 0.9})
Execution error (ClassCastException) at gen.distribution.commons-math/categorical-distribution (commons_math.clj:102).
class clojure.lang.MapEntry cannot be cast to class java.lang.Number (clojure.lang.MapEntry is in unnamed module of loader 'app'; java.lang.Number is in module java.base of loader 'bootstrap')
```

This could be emulated if combined with a `case` statement but that would require the user to track the mapping between categories returned and the `case` index for every single categorical in all the models they have if they would like to condition the model. That's a high burden for users of structure learning who maintain many models with hundreds of categoricals each.

**Comment by sritchie** [comment]
@Schaechtle this is a good idea! Many of these should actually be taking maps, imo, so that there's no ambiguity about argument order.
